create table langs (
  id integer primary key autoincrement,
  lang text not null unique,
  code  text not null unique
) strict;

insert into langs (lang, code) values ('Afrikaans', 'af');
insert into langs (lang, code) values ('Albanian',	'sq');
insert into langs (lang, code) values ('Amharic',	'am');
insert into langs (lang, code) values ('Arabic',	'ar');
insert into langs (lang, code) values ('Armenian',	'hy');
insert into langs (lang, code) values ('Assamese',	'as');
insert into langs (lang, code) values ('Aymara',	'ay');
insert into langs (lang, code) values ('Azerbaijani',	'az');
insert into langs (lang, code) values ('Bambara',	'bm');
insert into langs (lang, code) values ('Basque',	'eu');
insert into langs (lang, code) values ('Belarusian',	'be');
insert into langs (lang, code) values ('Bengali',	'bn');
insert into langs (lang, code) values ('Bhojpuri',	'bho');
insert into langs (lang, code) values ('Bosnian',	'bs');
insert into langs (lang, code) values ('Bulgarian',	'bg');
insert into langs (lang, code) values ('Catalan',	'ca');
insert into langs (lang, code) values ('Cebuano',	'ceb');
insert into langs (lang, code) values ('Chinese (Simplified)', 'zh-CN or zh (BCP-47)');
insert into langs (lang, code) values ('Chinese (Traditional)', 'zh-TW (BCP-47)');
insert into langs (lang, code) values ('Corsican',	'co');
insert into langs (lang, code) values ('Croatian',	'hr');
insert into langs (lang, code) values ('Czech',	'cs');
insert into langs (lang, code) values ('Danish',	'da');
insert into langs (lang, code) values ('Dhivehi',	'dv');
insert into langs (lang, code) values ('Dogri',	'doi');
insert into langs (lang, code) values ('Dutch',	'nl');
insert into langs (lang, code) values ('English',	'en');
insert into langs (lang, code) values ('Esperanto',	'eo');
insert into langs (lang, code) values ('Estonian',	'et');
insert into langs (lang, code) values ('Ewe',	'ee');
insert into langs (lang, code) values ('Filipino (Tagalog)', 'fil');
insert into langs (lang, code) values ('Finnish',	'fi');
insert into langs (lang, code) values ('French',	'fr');
insert into langs (lang, code) values ('Frisian',	'fy');
insert into langs (lang, code) values ('Galician',	'gl');
insert into langs (lang, code) values ('Georgian',	'ka');
insert into langs (lang, code) values ('German',	'de');
insert into langs (lang, code) values ('Greek',	'el');
insert into langs (lang, code) values ('Guarani',	'gn');
insert into langs (lang, code) values ('Gujarati',	'gu');
insert into langs (lang, code) values ('Haitian Creole', 'ht');
insert into langs (lang, code) values ('Hausa',	'ha');
insert into langs (lang, code) values ('Hawaiian',	'haw');
insert into langs (lang, code) values ('Hebrew',	'he or iw');
insert into langs (lang, code) values ('Hindi',	'hi');
insert into langs (lang, code) values ('Hmong',	'hmn');
insert into langs (lang, code) values ('Hungarian',	'hu');
insert into langs (lang, code) values ('Icelandic',	'is');
insert into langs (lang, code) values ('Igbo',	'ig');
insert into langs (lang, code) values ('Ilocano',	'ilo');
insert into langs (lang, code) values ('Indonesian',	'id');
insert into langs (lang, code) values ('Irish',	'ga');
insert into langs (lang, code) values ('Italian',	'it');
insert into langs (lang, code) values ('Japanese',	'ja');
insert into langs (lang, code) values ('Javanese',	'jv or jw');
insert into langs (lang, code) values ('Kannada',	'kn');
insert into langs (lang, code) values ('Kazakh',	'kk');
insert into langs (lang, code) values ('Khmer',	'km');
insert into langs (lang, code) values ('Kinyarwanda',	'rw');
insert into langs (lang, code) values ('Konkani',	'gom');
insert into langs (lang, code) values ('Korean',	'ko');
insert into langs (lang, code) values ('Krio',	'kri');
insert into langs (lang, code) values ('Kurdish',	'ku');
insert into langs (lang, code) values ('Kurdish (Sorani)', 'ckb');
insert into langs (lang, code) values ('Kyrgyz',	'ky');
insert into langs (lang, code) values ('Lao',	'lo');
insert into langs (lang, code) values ('Latin',	'la');
insert into langs (lang, code) values ('Latvian',	'lv');
insert into langs (lang, code) values ('Lingala',	'ln');
insert into langs (lang, code) values ('Lithuanian',	'lt');
insert into langs (lang, code) values ('Luganda',	'lg');
insert into langs (lang, code) values ('Luxembourgish',	'lb');
insert into langs (lang, code) values ('Macedonian',	'mk');
insert into langs (lang, code) values ('Maithili',	'mai');
insert into langs (lang, code) values ('Malagasy',	'mg');
insert into langs (lang, code) values ('Malay',	'ms');
insert into langs (lang, code) values ('Malayalam',	'ml');
insert into langs (lang, code) values ('Maltese',	'mt');
insert into langs (lang, code) values ('Maori',	'mi');
insert into langs (lang, code) values ('Marathi',	'mr');
insert into langs (lang, code) values ('Meiteilon (Manipuri)', 'mni-Mtei');
insert into langs (lang, code) values ('Mizo',	'lus');
insert into langs (lang, code) values ('Mongolian',	'mn');
insert into langs (lang, code) values ('Myanmar (Burmese)', 'my');
insert into langs (lang, code) values ('Nepali',	'ne');
insert into langs (lang, code) values ('Norwegian',	'no');
insert into langs (lang, code) values ('Nyanja (Chichewa)', 'ny');
insert into langs (lang, code) values ('Odia (Oriya)', 'or');
insert into langs (lang, code) values ('Oromo',	'om');
insert into langs (lang, code) values ('Pashto',	'ps');
insert into langs (lang, code) values ('Persian',	'fa');
insert into langs (lang, code) values ('Polish',	'pl');
insert into langs (lang, code) values ('Portuguese (Portugal, Brazil)', 'pt');
insert into langs (lang, code) values ('Punjabi',	'pa');
insert into langs (lang, code) values ('Quechua',	'qu');
insert into langs (lang, code) values ('Romanian',	'ro');
insert into langs (lang, code) values ('Russian',	'ru');
insert into langs (lang, code) values ('Samoan',	'sm');
insert into langs (lang, code) values ('Sanskrit',	'sa');
insert into langs (lang, code) values ('Scots Gaelic', 'gd');
insert into langs (lang, code) values ('Sepedi',	'nso');
insert into langs (lang, code) values ('Serbian',	'sr');
insert into langs (lang, code) values ('Sesotho',	'st');
insert into langs (lang, code) values ('Shona',	'sn');
insert into langs (lang, code) values ('Sindhi',	'sd');
insert into langs (lang, code) values ('Sinhala (Sinhalese)', 'si');
insert into langs (lang, code) values ('Slovak',	'sk');
insert into langs (lang, code) values ('Slovenian',	'sl');
insert into langs (lang, code) values ('Somali',	'so');
insert into langs (lang, code) values ('Spanish',	'es');
insert into langs (lang, code) values ('Sundanese',	'su');
insert into langs (lang, code) values ('Swahili',	'sw');
insert into langs (lang, code) values ('Swedish',	'sv');
insert into langs (lang, code) values ('Tagalog (Filipino)', 'tl');
insert into langs (lang, code) values ('Tajik',	'tg');
insert into langs (lang, code) values ('Tamil',	'ta');
insert into langs (lang, code) values ('Tatar',	'tt');
insert into langs (lang, code) values ('Telugu',	'te');
insert into langs (lang, code) values ('Thai',	'th');
insert into langs (lang, code) values ('Tigrinya',	'ti');
insert into langs (lang, code) values ('Tsonga',	'ts');
insert into langs (lang, code) values ('Turkish',	'tr');
insert into langs (lang, code) values ('Turkmen',	'tk');
insert into langs (lang, code) values ('Twi (Akan)', 'ak');
insert into langs (lang, code) values ('Ukrainian',	'uk');
insert into langs (lang, code) values ('Urdu',	'ur');
insert into langs (lang, code) values ('Uyghur',	'ug');
insert into langs (lang, code) values ('Uzbek',	'uz');
insert into langs (lang, code) values ('Vietnamese',	'vi');
insert into langs (lang, code) values ('Welsh',	'cy');
insert into langs (lang, code) values ('Xhosa',	'xh');
insert into langs (lang, code) values ('Yiddish',	'yi');
insert into langs (lang, code) values ('Yoruba',	'yo');
insert into langs (lang, code) values ('Zulu',	'zu');
